### ISSUE TITLE
Weight shows inf

### ISSUE THREAD

**Issue by BSass** [jebril76/OctoPrint-SmartScale#4] opened 2020-04-02 18:54 UTC
I have the problem, that I do not get any value for the weigth. The smartScale plugin shows inf and the display "inf" or "nan".
Temperature values are shown correctly. 
I use the parts from your BOM. Two 5 kg load cells and a HX711.

**Comment by jebril76** [comment] 2020-04-10 14:00
Hi Bsass, 
thanks for your interest. 

"Nan" is shown, when the Hx711 is not recognized by the ESP8266. Check your wiring.
"Inf" is shown, when the values transmitted by the Hx711 are not valid. Check the orientation of the loadcells and recalibrate the scale.

Thanks to your question I have added this information to the Wiki under Troubleshooting.

Please let me know it you got it sorted. Thanks!

If i do not get other info i will close this on 17.04.20.



Liebe Grüße aus Köln.

**Comment by BSass** [comment] 2020-04-12 16:59
Thanks for your help. I changed the orientation of the load cells, but that has not helped.
But I have sent the serial commands for tare and calibrate with putty and now I get proper values.
There seems to be a problem in the smartScale octoprint plugin. It doesn't seem to connect properly to the serial port, but it shows no error message in the user interface. 
In the octoprint.log I can find such error messages which confirm the problem:

> 2020-04-12 17:48:07,181 - octoprint.server.api - ERROR - Error while executing SimpleApiPlugin SmartScale
> Traceback (most recent call last):
>   File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint/server/api/__init__.py", line 109, in pluginCommand
>     response = api_plugin.on_api_command(command, data)
>   File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_SmartScale/__init__.py", line 170, in on_api_command
>     self.usbCon.write("<dens:%.8f>" % float(data["dens"]))
>   File "/home/pi/oprint/local/lib/python2.7/site-packages/serial/serialposix.py", line 571, in write
>     raise SerialException('write failed: {}'.format(e))
> SerialException: write failed: [Errno 5] Input/output error
> 

Is there a way to set the correct serial port?

Liebe Grüße aus Flensburg

**Comment by jebril76** [comment] 2020-04-12 17:50
My pleasure!
This error message (init.py - Line 170) is not related to the connection process. It's part of the "Load Settings" process. This should only be available after a successful connection. Seems to me like the connection is established and then lost again. This might happen due to a long and/or unshielded USB-Cable. The filament status should show the message "Connection lost".

1) Could you search the logs for this line: "SmartScale connected to Port:". If you find it a valid connection was established. You might also check wether the given USB-Port is the one connected to your ESP.
2) In case it's not the right USB-Port, could you try to reboot your system with only the scale connected to your device (no Printer/Cam/ect.) just to make sure no other device is interfering.
3) Could you do a test with a shorter and shielded USB-Cable without the watertight usb panel mount?
4) Could you remove the "##" from line 112 of init.py, restart octoprint and check the logs. The measured values should should now be logged in the logfile.
5) If there is a problem with establishing a connection, there should be an error in the logfiles regarding the file init.py between Line 61 and 144. 

Thanks for your effort.

**Comment by BSass** [comment] 2020-04-12 20:38
When I restart octoprint it connects and shows the temperature (in the log and in the settings page). When a command is sent from the plugin to the scale it stopps updating the temperature (and there are also no more log entries): 

> 2020-04-12 21:28:22,084 - octoprint.plugins.SmartScale - INFO - [U:1277.08;W:800.73;L:267.95;T:25.20;R:32.45;A:79.87;P:1014.59]
> 2020-04-12 21:28:22,090 - octoprint.plugins.SmartScale - INFO - Density set to 1.24
The reconnect button does not solve the problem. 

When I then restart octoprint it connects again and shows updates. I have activated the VERBOSE flag in your firmware. Could that cause the problem?

Changing the usb cable does not help. 

Why do you need the coil weigth? When I calibrate the scale, I use tare with the empty coil installed. So the coil weigth should be irrelevant for further measurements.

**Comment by jebril76** [comment] 2020-04-13 09:56
The verbose flag should not be problematic. 
The serial connection is established without any problems. 
A problem with the cable would result in connection losses from time to time ... but not only when sending commands.

I suppose you used SmartScale_USB to flash the ESP (Not SmartScale_Wifi) - as described in the Wiki. Wifi is still WIP.

Unfortunatly I am still not able to reproduce your error (second Post). Could you please provide some more the logs. Perhaps some errors from the tare or calibration process.

Are you running a Rpi3b+ or a Pri4b?
Are you running Octopi 0.17?

You could also test the 2 following things:
1) Reduce Baudrate in line 70 from 115200 to 9600.
2) Comment line 170 (and 171) with a "##" in the beginning.

If you want we can communicate in german - or via VoiceChat. I'm eager to get it running for you. But as long as i can't reproduce the error it is very difficult.

**Comment by BSass** [comment] 2020-04-14 13:45
Auf deutsch ist es wohl einfacher ;-)
Ich benutze SmartScale_USB.

Für OctoPi benutze ich einen Rpi3b+.
Bis jetzt hatte ich octopi 0.16 drauf.
Ich habe mir jetzt mal die Mühe gemacht und ein frisches 0.17 installiert. Allerdings mit dem gleichen Ergebnis:
Er erkennt die Waage beim Start von octoprint und liefert auch permanent Messwerte. Sobald ich allerdings irgendeinen Befehl sende, bekomme ich keine Aktualisierung der Werte mehr.
Die gesendeten Befehle kommen aber scheinbar an. Habe das gerade nochmal mit nem tare und calibrate getestet. Sobald ich auch tare geklickt habe, gibt es keine neuen Werte mehr. Wenn ich dann noch auf calibrate klicke und octoprint neu starte, gibt es wieder Werte und die Kalibrierung wurde auch übernommen. Das gleiche passiert natürlich auch bei einem Rollenwechsel, etc.

Im log steht leider nichts brauchbares:

> 2020-04-14 14:33:27,739 - octoprint.plugins.SmartScale - INFO - SmartScale connected to Port:/dev/ttyUSB0
> 2020-04-14 14:33:28,369 - octoprint.plugins.SmartScale - INFO - [U:935.32;W:699.40;L:234.04;T:24.51;R:27.46;A:65.01;P:1024.42]
> ...
> 2020-04-14 14:33:54,320 - octoprint.plugins.SmartScale - INFO - [U:934.84;W:699.40;L:234.04;T:24.49;R:27.36;A:64.70;P:1024.41]
> 2020-04-14 14:33:54,549 - octoprint.plugins.SmartScale - INFO - [U:935.12;W:699.40;L:234.04;T:24.50;R:27.43;A:64.90;P:1024.43]
> 2020-04-14 14:33:55,055 - octoprint.plugins.SmartScale - INFO -

Es stoppt halt einfach wenn ein Befehl gesendet wird.

**Comment by jebril76** [comment] 2020-04-18 13:57
Das Plugin aktualisiert nicht mehr. Die Anzeige auf dem Display läuft weiter richtig?

Ohne den Fehler bei mir reproduzieren zu können und ohne Fehlermeldung komme ich ohne deine Hilfe nicht weiter.
Wir bauen mal ein paar Log-Ausgaben ein um zu schauen, an welcher Stelle er seinen Dienst beendet:
Ersetze mal in init.py Zeile 147 bis 153 durch:

		self._logger.info("command send")
		import flask
		self._logger.info("flask loaded")
		if command == 'reconnect' and self.usbCon == None:
    		self._logger.info("reconnect pressed")
			self.error=""
			self.connect()
    		self._logger.info("reconnect done")
		if self.usbCon != None:
			if command == 'tare':
				self._logger.info("tare started")
				self.usbCon.write("<tara:1>".encode())
				self._logger.info("tare send")

Teste das Plugin mit den Tare-Commando und dem Reconnect und schick mir das Log.

Danke!

**Comment by BSass** [comment] 2020-04-18 14:32
Ja, genau.

Mit dem neuen Code erhalten ich folgenden log:

> 2020-04-18 15:29:51,294 - octoprint.plugins.SmartScale - INFO - [U:-0.32;W:0.00;L:0.00;T:24.82;R:32.41;A:78.09;P:1021.85]
> 2020-04-18 15:29:51,303 - octoprint.plugins.SmartScale - INFO - [U:-0.03;W:0.00;L:0.00;T:24.83;R:32.44;A:78.19;P:1021.86]
> 2020-04-18 15:29:51,471 - octoprint.plugins.SmartScale - INFO - [U:-0.64;W:0.00;L:0.00;T:24.83;R:32.49;A:78.32;P:1021.86]
> 2020-04-18 15:29:51,703 - octoprint.plugins.SmartScale - INFO - [U:-0.44;W:0.00;L:0.00;T:24.83;R:32.45;A:78.21;P:1021.85]
> 2020-04-18 15:29:51,799 - octoprint.plugins.SmartScale - INFO - command send
> 2020-04-18 15:29:51,801 - octoprint.plugins.SmartScale - INFO - flask loaded
> 2020-04-18 15:29:51,802 - octoprint.plugins.SmartScale - INFO - tare started
> 2020-04-18 15:29:51,805 - octoprint.plugins.SmartScale - INFO - tare send
> 2020-04-18 15:29:51,931 - octoprint.plugins.SmartScale - INFO - [U:-0.31;W:0.00;L:0.00;T:24.83;R:32.39;A:78.08;P:1021.86]
>

**Comment by jebril76** [comment] 2020-04-19 13:18
Ok, das ist sehr ungewöhnlich. Er durchläuft den ganzen Tare Prozess, dann einen weiteren Update-Prozess und steigt erst danach aus - obwohl die Infos vom ESP genau das gleiche Format wie vorher haben. Bitte prüfe nochmal, ob die Fehlermeldung im Status Block bei "Filament:" Connection lost und nicht "No Data" oder "Corrupt Data" anzeigt.

Er scheint bei der While-Schleife von Zeile 109 bis 137 die Verbindung zu verlieren. Du kannst gerne in Zeile 134 mal OSError und mal Serial.SerialException raus nehmen. Ich werde hier auch noch mal was probieren und mich bald nochmal melden.

**Comment by BSass** [comment] 2020-04-19 15:05
Ich hab das Problem gefunden. Scheinbar kam das Plugin doch nicht mit der Antwort klar:

> 2020-04-19 15:45:55,769 - octoprint.plugins.SmartScale - INFO - Received line "[U:2.25;W:0.00;L:0.00;T:25.90;R:24.32;A:62.24;P:1028.22]"
> 2020-04-19 15:45:55,942 - octoprint.plugins.SmartScale - INFO - command send
> 2020-04-19 15:45:55,944 - octoprint.plugins.SmartScale - INFO - flask loaded
> 2020-04-19 15:45:55,946 - octoprint.plugins.SmartScale - INFO - tare started
> 2020-04-19 15:45:55,950 - octoprint.plugins.SmartScale - INFO - tare send
> 2020-04-19 15:45:55,998 - octoprint.plugins.SmartScale - INFO - Received line "[U:2.09;W:0.00;L:0.00;T:25.90;R:24.28;A:62.15;P:1028.25]"
> 2020-04-19 15:45:56,508 - octoprint.plugins.SmartScale - INFO - Received line ""
> 2020-04-19 15:45:56,781 - octoprint.plugins.SmartScale - INFO - Received line "Tara"
> 2020-04-19 15:45:57,024 - octoprint.plugins.SmartScale - INFO - Received line "[U:0.00;W:0.00;L:0.00;T:25.90;R:24.34;A:62.29;P:1028.25]"
> 2020-04-19 15:45:57,254 - octoprint.plugins.SmartScale - INFO - Received line "[U:0.34;W:0.00;L:0.00;T:25.90;R:24.29;A:62.18;P:1028.24]"

Nach dem Senden des Befehls kommt noch einmal ein normaler Wert und danach folgt eine leere Zeile und danach noch aus dem verbose das "Tara". Er schien sich schon an der leeren Zeile vorher aufzuhängen. Ich hab nicht genau verstanden aus was das "if line" prüft.

Als Quickfix habe ich hier hinter:
```
                        try:
                                line = self.usbCon.readline().strip().decode('ascii')
                                self._logger.info('Received line "' + line + '"')
```

Das hier eingefügt:

                                while len(line) == 0 or not line.startswith('[U:') or not line.endswith(']'):
                                       line = self.usbCon.readline().strip().decode('ascii')
                                       self._logger.info('Received line "' + line + '"'



Ich verstehe allerdings immer noch nicht, wozu die Coil weigth angegeben wird. Ich führe das tara doch mit aufgelegter leerer coil durch, oder? Das bedeutet mein Messwert zeigt nur das Gewicht der Spule an. Davon darf doch dann nicht mehr die Coil abgezogen werden?

**Comment by jebril76** [comment] 2020-04-20 15:46
Super! 
Eigentlich sollten Leerzeilen und andere fehlerhafte Daten über USB nicht direkt zum Abbruch führen. 
Erst wenn er 3 Sekunden keine sinnvollen Daten erhält gibt es einen "Corrupt Data" - Fehler. (if time.time()-timer>3). Anscheinend muss da noch ein Fehler sein. Ich werde mir das später nochmal genauer anschauen und dann ein Update für den ESP und das Plugin raushauen.

Vielen Dank für Deine Hilfe und sorry, dass es so lange gedauert hat. Ich nehme dich in die "Thanks-To" Liste auf.

Wenn du Verbesserungsvorschläge oder Änderungswünsche hast, dann immer raus damit. 

Eine Frage war noch unbeantwortet: Warum CoilWeight? Ist so gewachsen. Habe überlegt es raus zu nehmen. Aber vielleicht gibt es Leute die verschiedene Waagen/Coils verwenden. Das Pugin ist ja nicht auf meine Waage beschränkt. 

Vielen Dank! Liebe Grüße und ich hoffe wir bleiben in Kontakt.

**Comment by BSass** [comment] 2020-04-20 16:30
Immer gerne.
Wenn man deiner Anleitung folgt, dann misst man das coil weigth, platziert dann die leere coil auf der Waage, löst das tare aus und calibriert dann mit einer vollen Rolle.
Und wenn ich das richtig sehe zieht deine Software von dem gemessenen Wert noch die coil weight ab. Dadurch stimmt das Ergebnis natürlich nicht mehr.
Also solltest du deine Anleitung in der Hinsicht anpassen, dass das tare ohne coil gemacht werden soll. Dann stimmt auch das Ergebnis wieder.

Vielen Dank für das schöne Projekt. Dann werde ich in den nächsten Tagen mal alles vom Breadboard nehmen, schön verlöten und in dem Fach verstauen.

Wir können gerne in Kontakt bleiben.

**Comment by jebril76** [comment] 2020-04-27 14:27
I updated the firmware.bin file. So it should run without problems now. Will close this issue after i have adressed the mistake in the step by step calibrationguide. Thanks for your effort BSass!

**Comment by jebril76** [comment] 2020-05-05 15:51
Should be alright now. Thanks for your help.

**Comment by jebril76** [comment] 2020-05-16 10:09
Added step to calibration guide for Coilweight.
Adjusted USB-read_timeout and write_timeout
Modified accuracy of tare and calibrate process in ESP-Firmware to reduce USB-response time.

**Closed as completed** 2020-05-16 11:02 UTC
